#
# export run_task to support LLM agent operation, init with CamelAI
#

import sys
import os
import logging

# from dotenv import load_dotenv

from camel.models import ModelFactory
from camel.toolkits import (
    SearchToolkit,
    BrowserToolkit,
    FileWriteToolkit,
    TerminalToolkit,
    # ImageAnalysisToolkit,
    # VideoAnalysisToolkit,
    # CodeExecutionToolkit,
)
from camel.types import ModelPlatformType, ModelType
from camel.logger import set_log_level

# from owl.utils import run_society
from owl.utils import run_chimera_society #, DocumentProcessingToolkit
from camel.societies import RolePlaying

import config

set_log_level(level="DEBUG")

def construct_society(question: str, output_dir: str, temperature: float = 0) -> RolePlaying:
    r"""Construct a society of agents based on the given question.

    Args:
        question (str): The task or question to be addressed by the society.
        output_dir (str): Directory for intermediate files and results.
        temperature (float): Sampling temperature. Use 0 for deterministic
            operations (scheduling, meetings) and 0.7 for creative or
            strategic tasks (attack execution, multi-step planning).

    Returns:
        RolePlaying: A configured society of agents ready to address the
            question.
    """

    ### For camel
    foundation_corp_map = {
            "openai": ModelType.GPT_4O_MINI,
            "google": ModelType.GEMINI_2_0_FLASH,
            "deepseek": ModelType.DEEPSEEK_CHAT,
        }
    foundation_model_platorm_map = {
            "openai": ModelPlatformType.OPENAI,
            "google": ModelPlatformType.GEMINI,
            "deepseek": ModelPlatformType.DEEPSEEK,
        }
    model_type_selection = foundation_corp_map.get(config.foundation_corp, ModelType.GPT_4O_MINI)
    model_platform_selection = foundation_model_platorm_map.get(config.foundation_corp, ModelPlatformType.DEFAULT)

    # Create models for different components
    models = {
        "user": ModelFactory.create(
            model_platform=model_platform_selection,
            model_type=model_type_selection,
            model_config_dict={"temperature": temperature},
        ),
        "assistant": ModelFactory.create(
            model_platform=model_platform_selection,
            model_type=model_type_selection,
            model_config_dict={"temperature": temperature},
        ),
        "browsing": ModelFactory.create(
            model_platform=model_platform_selection,
            model_type=model_type_selection,
            model_config_dict={"temperature": 0},
        ),
        "planning": ModelFactory.create(
            model_platform=model_platform_selection,
            model_type=model_type_selection,
            model_config_dict={"temperature": 0},
        ),
    }

    # Configure toolkits
    tools = [
        *FileWriteToolkit(output_dir=output_dir).get_tools(),
        *TerminalToolkit(working_dir=output_dir, log_path=output_dir, need_terminal=False).get_tools(),
    ]
    if not config.offline_mode:
        tools += [
            *BrowserToolkit(
                headless=True,
                web_agent_model=models["browsing"],
                planning_agent_model=models["planning"],
                cache_dir=output_dir,
            ).get_tools(),
            SearchToolkit().search_duckduckgo,
            SearchToolkit().search_google,
        ]

    # Configure agent roles and parameters
    user_agent_kwargs = {"model": models["user"]}
    assistant_agent_kwargs = {"model": models["assistant"], "tools": tools}

    # Configure task parameters
    task_kwargs = {
        "task_prompt": question,
        "with_task_specify": False,
    }

    # Create and return the society
    society = RolePlaying(
        **task_kwargs,
        user_role_name="user",
        user_agent_kwargs=user_agent_kwargs,
        assistant_role_name="assistant",
        assistant_agent_kwargs=assistant_agent_kwargs,
    )

    return society

def run_task(week: int, date: str, task: str, member_id: str, log_dir: str, event_index: int, output_dir: str, temperature: float = 0) -> str:
    r"""Run the OWL system with a given task.

    Args:
        task (str): The task or question to be addressed.
        temperature (float): Sampling temperature passed to construct_society.
            Use 0 for deterministic tasks and 0.7 for attack/strategic tasks.

    Returns:
        str: The answer generated by the society.
    """
    # Construct and run the society
    # output_dir saves all the intermediate files and result during the execution
    society = construct_society(task, output_dir, temperature)
    os.makedirs(log_dir, exist_ok=True)
    detailed_log = os.path.join(log_dir, f"{member_id}_week_{week}_{date}_executio_task_{event_index}.log")
    # Configure a FileHandler for the logger
    file_handler = logging.FileHandler(detailed_log, mode="w")
    file_handler.setLevel(logging.INFO)
    file_formatter = logging.Formatter("%(asctime)s - %(levelname)s - %(message)s")
    file_handler.setFormatter(file_formatter)

    logger = logging.getLogger()
    logger.addHandler(file_handler)

    try:
        answer, chat_history, token_count = run_chimera_society(
            society,
            round_limit=config.round_limit,
            member_id=member_id,
            log_dir=log_dir,
            event_index=event_index,
            week=week,
            date=date,
        )
    finally:
        # Remove the file handler after use
        logger.removeHandler(file_handler)

    return answer

if __name__ == "__main__":
    
    # r"""Main function to run the OWL system with an example question."""
    # # Default research question
    default_task = "Navigate to camel.ai, count the paper numbers has been published. No need to verify your answer."

    # # Override default task if command line argument is provided
    # task = sys.argv[1] if len(sys.argv) > 1 else default_task

    # # Construct and run the society
    # society = construct_society(task)
    # answer, chat_history, token_count = run_society(society)

    # # Output the result
    # print(f"\033[94mAnswer: {answer}\033[0m")